### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by JivanRoquet** [kakkun61/postgresql-pure#2]
Is there any place where we can read about how to use this library?

**Comment by kakkun61** [comment]
@JivanRoquet Sorry for my late reply.

There are no standalone documents. There are:

- Haddock
  - https://hackage.haskell.org/package/postgresql-pure/
  - a main content is [Database.PostgreSQL.Pure](https://hackage.haskell.org/package/postgresql-pure-0.2.3.0/docs/Database-PostgreSQL-Pure.html)
- Specs
  - https://github.com/kakkun61/postgresql-pure/tree/master/test-original
  - a main content is [Database.PostgreSQL.PureSpec](https://github.com/kakkun61/postgresql-pure/blob/master/test-original/Database/PostgreSQL/PureSpec.hs)
- and, a blog post but in Japanese
  - https://kakkun61.hatenablog.com/entry/2019/12/06/postgresql-pure_%E3%82%92%E9%96%8B%E7%99%BA%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F
